Iter13
Melikhov-p/url-minimise pull request #13
Opened 2024-11-28 15:10 UTC by Melikhov-p

2024-11-30 14:34 UTC, s-shpak requested changes

2024-11-30 14:34 UTC, s-shpak commented on cmd/shortener/main.go
> +	cfg.Build()               // Забирает значения флагов и переменных окружения
А почему эти два действия нельзя сделать одновременно ?

2024-11-30 14:34 UTC, s-shpak commented on internal/app/router.go
> +	pingDBWrapper := func(w http.ResponseWriter, r *http.Request) {
Стилистическое: я бы посоветовла объявить функцию прямо внутри `router.Get`

2024-11-30 14:34 UTC, s-shpak commented on internal/config/config.go
> +		log.Println("Database mode ON")
После перехода на `zap` не используй `log` (исключение -- при логгировании до инициализации коревого логгера)

2024-11-30 14:34 UTC, s-shpak commented on internal/handlers/handlers.go
> +	if err = storage.AddURL(ctx, newURL); err != nil {
Кажется, что это логика, которую стоит вынести на слой бизнес-логики (похоже, его пора добавлять)

2024-11-30 14:34 UTC, s-shpak commented on internal/handlers/handlers.go
> +	logger *zap.Logger) {
```suggestion
	logger *zap.Logger,
) {
```

2024-11-30 14:34 UTC, s-shpak commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
Эта проверка до сих пор нужна ? Без нее падают автотесты ?

2024-11-30 14:34 UTC, s-shpak commented on internal/handlers/handlers.go
> +	if cfg.StorageMode != storagePkg.StorageInDatabase {
Я бы все три хранилища сделал с одним и тем же интерфейсом, и память/файл просто возвращали бы `nil` при вызове `Ping`: не произошло никакой нештатной ситуации, локальное хранилище (в памяти или в файле) доступно

2024-11-30 14:34 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +var CFG *config.Config = config.NewConfig()
Не используй глобальные переменные, можно инициализировать этот объект для каждого теста, это недорого и лучше изолирует тесты

2024-11-30 14:34 UTC, s-shpak commented on internal/repository/storage_repo.go
> +		ok, err := dbCheckTable(ctx, store.DB, dbTableName)
Если внутри одной операции ты делаешь несколько запросов к БД, то эти запросы необходимо оборачивать в транзацкию (даже если это запросы на чтение).

Если не делать этого, то ты рикуешь столкнуться с малопонятными багами из-за data-race'ов.

2024-11-30 14:34 UTC, s-shpak commented on internal/repository/storage_repo.go
> +func createTable(ctx context.Context, db *sql.DB) error {
Используй механизм миграций для создания схемы БД

2024-11-30 14:34 UTC, s-shpak commented on internal/storage/database.go
> +		if strings.Contains(err.Error(), UniqueViolationCode) {
Unique violation может теоретически произойти не из-за того, что URL уже существует, а из-за другого поля. Подумай, как различать коллизию из-за URL и любую другю unique violation ошибку

2024-12-01 10:04 UTC, Melikhov-p commented on internal/handlers/handlers.go
> +	if cfg.StorageMode != storagePkg.StorageInDatabase {
> Я бы все три хранилища сделал с одним и тем же интерфейсом, и память/файл просто возвращали бы `nil` при вызове `Ping`: не произошло никакой нештатной ситуации, локальное хранилище (в памяти или в файле) доступно

Все три хранилища и так реализуют один и тот же интерфейс Storage, я просто думал, что здесь эта проверка имеет смысл

2024-12-01 12:17 UTC, Melikhov-p commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
да, вместо 405 приходит 404 местами, местами приходит успешный код, как будто все норм

2024-12-04 08:45 UTC, Melikhov-p commented on internal/handlers/handlers.go
> +	if err = storage.AddURL(ctx, newURL); err != nil {
Я все же решил идею с менеджером транзакций отложить пока, потому что начинается новый спринт, да и с наскока въехать как-то не получилось, я подумал - оставлю это для какого-нибудь промежуточного проекта, тут ради одного сценария добавления урла сильно закапываться не буду. Поэтому просто немного логику поменял, теперь сначала проверка, что урл уже существует, и если нет - добавляем новый, и все в рамках одной транзакции.

2024-12-04 20:28 UTC, s-shpak requested changes

2024-12-04 20:28 UTC, s-shpak commented on internal/storage/memory.go
> +	return "", ErrNotFound
Здесь к ошибке лучше добавить контекст

2024-12-04 20:28 UTC, s-shpak commented on internal/storage/memory.go
>  	DB map[string]*models.StorageURL
Кажется, что это поле не должно быть экспортируемым

2024-12-04 20:28 UTC, s-shpak commented on internal/storage/database.go
> +	preparedInsert, err := tx.PrepareContext(ctx, `
Это не совсем батчинг: батчинг предполагает отправку одного запроса для создания нескольких сущностей (количество сущностей = размеру батча).

В случае использования `sql.DB` тебе придется генерировать запрос вручную (см. https://stackoverflow.com/questions/12486436/how-do-i-batch-sql-statements-with-package-database-sql), т.к. в пакете из стандартной библиотеки нет методов для батчинга.

2024-12-04 20:28 UTC, s-shpak commented on internal/storage/storage.go
>  	BaseStorage StorageType = iota
Кажется, что проверку можно сделать без обхявления этого enum: просто объект конфигурации для выбранного хранилища не будет равен nil, в отличие от других типов хранилищ

2024-12-05 09:07 UTC, Melikhov-p commented on internal/storage/memory.go
>  	DB map[string]*models.StorageURL
оно используется в пакете repository для создания хранилища, а если сделать функцию конструкцию NewMemoryStorage, а memoryStorage станет неэкспортируемым, то IDE будет жаловаться, что я в экспортируемой функции возвращаю неэкспортируемый тип

2024-12-05 09:14 UTC, Melikhov-p commented on internal/storage/storage.go
>  	BaseStorage StorageType = iota
имея в распоряжении специальное поле для типа хранилища, мне как минимум удобней его потом строить с через `switch cfg.StorageMode` с вариантом где нужно искать не nil хранилище switch не пройдет, и если мне где-то ещё нужно будет проверить тип хранилища, то через отдельное поле это сделать удобней, я бы все таки хотел оставить так, если это не критично

2024-12-06 13:36 UTC, s-shpak commented on internal/storage/storage.go
>  	BaseStorage StorageType = iota
ОК, можешь оставить. Учитывай, что минус такого поля в том, что теперь источников правды о том, какого типа хранилище ты используешь, -- два. Это может приветси к проблемам.

Этот комментарий можно зарезолвить

2024-12-06 13:42 UTC, s-shpak commented on internal/storage/database.go
> +		placeholders = append(placeholders, fmt.Sprintf("('%s', '%s')", url.ShortURL, url.OriginalURL))
Так делать нельзя из-за потенциальной SQL-инъекции. В запросе на вставку данных тебе нужно всегда исползовать плейсхолдеры `$1` и передавать конкретные значения в качестве аргументов к Exec

2024-12-06 13:42 UTC, s-shpak commented on internal/storage/memory.go
>  	DB map[string]*models.StorageURL
Так пусть `MemoryStorage` остается экспортируемым, а его поле `DB` станет не экспортируемым. Тогда добавление "конструктора" для `MemoryStorage` будет иметь смысл

2024-12-06 13:43 UTC, s-shpak requested changes
См. комментарии

2024-12-08 22:24 UTC, s-shpak approved these changes

2024-12-10 14:43 UTC, merged