Iter15
Melikhov-p/url-minimise pull request #15
Opened 2024-12-17 11:43 UTC by Melikhov-p

2024-12-19 12:12 UTC, s-shpak requested changes

2024-12-19 12:12 UTC, s-shpak commented on internal/auth/main.go
Такие файлы не принято называть `main.go`, если это единственный файл в пакете, то его лучше назвать `auth.go`

2024-12-19 12:12 UTC, s-shpak commented on internal/handlers/url_handlers.go
> +			logger.Error("error authorizing user")
Ошибку надо добавить в лог

2024-12-19 12:12 UTC, s-shpak commented on internal/handlers/url_handlers.go
> +	tokenCookie, err := r.Cookie(cookieToken)
Перенеси всю логику индентификации пользователя в middleware. После идентификации необходимая информацию о пользователе должна находиться в контексте

2024-12-19 12:12 UTC, s-shpak commented on internal/handlers/url_handlers.go
> +	go func() {
Я рекомендую тебе воспользоваться паттерном Transactional outbox. См. здесь подробнее, что это значит: https://habr.com/ru/companies/lamoda/articles/678932/

Я предлагаю тебе воспользоваьтся БД и отдельной горутиной для реализации этого паттерна. Это позволит:
1. гарантированно удалять сообщения даже в случае перезапуска сервиса
2. снизить нагрузку на БД: теперь количество компонентов, которые работают с БД будет ограниченным. К тому же тебе не надо будет думать про блокировку конкуретных запросов к базе

Если тебе будет непонятно, о чем этот паттерн, то пиши в пачку.

2024-12-19 12:12 UTC, s-shpak commented on internal/service/user_service.go
> +	logger.Debug("auth by token", zap.String("TOKEN", tokenString), zap.Int("ID", userID))
Токен может быть конфиденциальным, не стоит писать его в логгер (даже на уровне `Debug`, т.к. можно ошибиться при конфигурации сервиса и все равно записать токен в лог на проде)

2024-12-19 12:12 UTC, s-shpak commented on internal/storage/database.go
> +	logger *zap.Logger) error {
```suggestion
	logger *zap.Logger,
) error {
```

2024-12-19 12:12 UTC, s-shpak commented on internal/storage/database.go
> +	query := fmt.Sprintf("UPDATE url SET is_deleted=true WHERE short_url IN (%s) AND user_id = $%d",
Этот запрос можно упростить: поменяй `user_id` и `short_url` местами, и передавай `user_id` напрямую в `ExecContext`

2024-12-19 12:12 UTC, s-shpak commented on internal/storage/database.go
> +func (db *DatabaseStorage) GetSecretKey(ctx context.Context) (string, error) {
По-моему в ТЗ не было требования хранить секретный ключ пользователя, или я ошибаюсь ?

2024-12-19 12:12 UTC, s-shpak commented on internal/storage/memory.go
> +		} else {
Сделай код более плоским

2024-12-19 14:03 UTC, Melikhov-p commented on internal/storage/database.go
> +func (db *DatabaseStorage) GetSecretKey(ctx context.Context) (string, error) {
Я все же бы это уже оставил, просто в таком случае и таблица пользователя в базе не нужна, да и проверять так удобней, в случае если сервер на тесте в панику падает, чтоб я мог все равно получить доступ к этим урл по апи с тем же токеном

2024-12-19 14:11 UTC, Melikhov-p commented on internal/storage/database.go
> +	query := fmt.Sprintf("UPDATE url SET is_deleted=true WHERE short_url IN (%s) AND user_id = $%d",
Если я все правильно понял, то переделав запрос на `UPDATE url SET is_deleted=true WHERE user_id = $1 AND 
 short_url IN (%s) ` и записывать в agrs только url, чтобы в дальнейшем вызывать его как `db.DB.ExecContext(ctx, query, userID, args...)` то так делать нельзя из-за ошибки `Invalid use of '...', the corresponding parameter is non-variadic`

2024-12-24 14:36 UTC, s-shpak requested changes

2024-12-24 14:36 UTC, s-shpak commented on internal/models/worker.go
> +	REGISTERED DelTaskStatus = "REGISTERED"
Константы в Go не принято называть заглавными буквами

2024-12-24 14:36 UTC, s-shpak commented on internal/worker/worker.go
> +func (dw *DelWorker) LookUp() {
Пока это делать не надо, но в будущем надо будет добавить graceful shutdown для воркеров. Этот комментарий можно зарезолвить

2024-12-24 21:07 UTC, s-shpak approved these changes

2024-12-25 10:58 UTC, merged