Iter5
Melikhov-p/url-minimise pull request #5
Opened 2024-10-28 09:50 UTC by Melikhov-p

2024-10-30 11:48 UTC, s-shpak requested changes

2024-10-30 11:48 UTC, s-shpak commented on internal/config/README.md
Ридми с инструкциями по запуску проекта лучше всего поместить в корень проекта

2024-10-30 11:48 UTC, s-shpak commented on cmd/client/main.go
> +	fmt.Println(users)
Не используй пакет `fmt`, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-10-30 11:48 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(fmt.Sprintf(`Internal Error %v`, err.Error()))
Паниковать не надо: используй `log.Fatal` для:
    1. отображения ошибки
    2. завершения процесса с ошибкой

2024-10-30 11:48 UTC, s-shpak commented on go.mod
Не забывай выполнять `go mod tidy` перед тем как пушить код в репозиторий (для этого можно настроить git-хуки)

2024-10-30 11:48 UTC, s-shpak commented on internal/config/flags.go
> +	srvEnvAddr, srvEnvExist := os.LookupEnv("SERVER_ADDRESS")
В Go принято проверять условия более лаконично:

```suggestion
	srvEnvAddr, ok := os.LookupEnv("SERVER_ADDRESS")
```

2024-10-30 11:48 UTC, s-shpak commented on internal/config/flags.go
> +	ServerAddr string
Не используй глобальные переменные. Ты можешь создавать объект с конфигурацией, наполнять его и передавать туда, где он будет использоваться

2024-10-30 11:48 UTC, s-shpak commented on internal/handlers/handlers.go
> +		log.Fatal(err)
`log.Fatal` завершает процесс с ненулевым кодом завершения (что указывает на то, что процесс завершился с ошибкой). Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса. 

Graceful shutdown мы будем делать позже, пока досаточно прокинуть ошибку до самого верхнего уровня.

2024-10-30 11:48 UTC, s-shpak commented on internal/handlers/handlers.go
> +	_, _ = fmt.Fprintf(w, `%s%s`, config.ResultAddr+"/", fullShortURL.ShortURL)
Ошибки нужно проверять

2024-10-30 11:48 UTC, s-shpak commented on internal/handlers/handlers.go
> +		if el.checkShortURL(id) {
Сейчас временная сложность поиска -- `O(n)`. Можно ли сделать лучше ?

2024-10-30 11:48 UTC, s-shpak commented on internal/handlers/handlers.go
> +		ShortURL: randomString(shortURLSize),
Что если сгенерируется случайнай строка, которая уже была сгенерирована раньше ?

2024-10-30 11:48 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +func TestGetFullURL(t *testing.T) {
Добавь `happy-path` тест: тест, когда ты добавляешь какую-то строку, а потом успешно ее извлекаешь

2024-10-30 11:58 UTC, s-shpak commented
Добавь в проект `golangci-lint` для линтинга. Здесь инструкции по тому, как это сделать: https://github.com/s-shpak/

2024-10-30 12:24 UTC, Melikhov-p commented on cmd/client/main.go
> +	fmt.Println(users)
А это не по заданию, это просто в процессе курса я пробовал разные штуки

2024-10-30 12:39 UTC, Melikhov-p commented on internal/config/flags.go
> +	srvEnvAddr, srvEnvExist := os.LookupEnv("SERVER_ADDRESS")
@s-shpak  как быть с 
```
resEnvAddr, resEnvExist := os.LookupEnv("BASE_URL")
```
ведь нужно проверить оба флага, тут можно оставить resEnvExist ?

2024-10-31 18:42 UTC, s-shpak commented on internal/config/flags.go
> +	srvEnvAddr, srvEnvExist := os.LookupEnv("SERVER_ADDRESS")
Делай проверку `ok` сразу после вызова `os.LookupEnv`. Вообще, хорошей практикой считается групировать логику близко, если это возможно

2024-10-31 18:48 UTC, s-shpak requested changes
Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-10-31 18:48 UTC, s-shpak commented on .golangci.yml
Этот файл не нужно пушить в репозиторий

2024-10-31 18:48 UTC, s-shpak commented on internal/config/config.go
>  	resEnvAddr, resEnvExist := os.LookupEnv("BASE_URL")
См. комментарий к старому треду

2024-10-31 18:48 UTC, s-shpak commented on internal/handlers/handlers.go
> +	return randomString(shortURLSize)
Не используй рекурсию без необходимости: это чревато очень неприятными паниками. Например, здесь, если ты исчерпаешь возможные случайные величины или сделаешь ошибку в `checkDuplicates`, после которой функция начент постоянно вызывать false, то приложение упадет со `stack overflow`.

Лучше просто в цикле генерировать новые строки, и если не получилось `n` раз, то просто возвращать ошибку

2024-11-06 17:53 UTC, s-shpak requested changes

2024-11-06 17:53 UTC, s-shpak commented on golangci-lint/report-unformatted.json
Извини, пожалуйста, когда я говорил про файл, который не нужно пушить в репозиторий, я имел в виду этот отчет. `.golangci.yaml` запушить как раз нужно

2024-11-07 10:50 UTC, s-shpak approved these changes

2024-11-07 17:06 UTC, merged