Iter9
Melikhov-p/url-minimise pull request #9
Opened 2024-11-15 12:25 UTC by Melikhov-p

2024-11-18 10:04 UTC, s-shpak requested changes

2024-11-18 10:04 UTC, s-shpak commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Я не советую использовать глобальный логгер. Такая практика встречается, но я предлагаю не использовать ее в курсе.

Единственный аргумент для использования глобального логгера -- возможность не передавать его напрямую в компоненты, где он используется. При этом использование глобального логгера несет в себе все минусы глобальных переменных, а также минусы самого глобального логгера.

Можно выделить две основные проблемы "глобального" подхода: 

1. Теперь ты не можешь кастомизировать логгер для конкретного компонента, в котором он используется. Например, если логгер явным образом передается в компонент при его инициализации, то ты можешь настроить его так, чтобы к каждому сообщению добавлялось поле с именем компонента, который это сообщение сгенерировал. Вобщем, локальные логгеры кастомизируются легко, глобальные -- сложно.

2. С одной стороны, удобно, что логгер не надо явным образом передавать в компонент. С другой, теперь мы создаем неявные зависимости: поведение компонента зависит от логгера (если, например, логгер не будет корректно проинициализирован, то компонент тоже поломается, т.к. при вызове логгера будет падать). Неявные зависимости хуже чем явные. Потому с моей т.з. передавать логгер явным образом как аргумент функции, или как поле объекта -- лучше, чем спрятать его в глобальную переменную

2024-11-18 10:04 UTC, s-shpak commented on internal/logger/logger.go
> +		return err
Ошибки надо оборачивать

2024-11-18 10:04 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatal("cannot run logger " + err.Error())
```suggestion
		log.Fatalf("cannot run logger: %v", err)
```

2024-11-18 10:04 UTC, s-shpak commented on internal/middlewares/middleware.go
> +	logFunc := func(w http.ResponseWriter, r *http.Request) {
```suggestion
	return func(w http.ResponseWriter, r *http.Request) {
```

2024-11-18 10:04 UTC, s-shpak commented on internal/middlewares/middleware.go
> +				cw := compress.NewCompressWrite(w)
```suggestion
				ow = compress.NewCompressWrite(w)
```

2024-11-18 10:04 UTC, s-shpak commented on internal/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
Это больше похоже на `Bad Request`

2024-11-18 10:04 UTC, s-shpak commented on internal/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
Здесь ошибку стоит залогировать

2024-11-18 10:04 UTC, s-shpak commented on internal/models/reqRes.go
Файлы в `go` принято называть либо `req_res.go`, либо `req-res.go`. Первый вариант более распространен, второй вариант более корректен: так нет риска случайно использовать какой-то зарезервированный build tag для файла.

2024-11-18 10:04 UTC, s-shpak commented on internal/models/storageURL.go
> +	file    *os.File
Кажется, что лучше было бы оставить memory store отдельно, а file store -- отдельно. File store расширяет функционал memory store, а не изменяет его, потому он может встраивать memory store в себя

2024-11-18 10:50 UTC, Melikhov-p commented on internal/middlewares/middleware.go
> +				cw := compress.NewCompressWrite(w)
Если так сделать то 
`if err := ow.Close(); err != nil {` даст ошибку, потому что ow не имеет такого метода, из-за того, что он все ещё http.ResponseWriter, поэтому тут только либо переопределять переменную под новый тип, либо оставить как есть

2024-11-20 09:03 UTC, s-shpak requested changes
Настрой, пожалуйста, `.golangci-lint` в Github Actions. Здесь, например, описано как: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-11-20 09:03 UTC, s-shpak commented on internal/logger/logger.go
> +// Никакой код навыка, кроме функции BuildLogger, не должен модифицировать эту переменную.
Этот комментарий устарел

2024-11-20 09:03 UTC, s-shpak commented on internal/models/storageURL.go
Здесь название файла также необходимо поменять

2024-11-20 09:03 UTC, s-shpak commented on internal/models/storageURL.go
> +var (
1. Это константы, а не переменные
2. Для таких перечисленний лучше использовать `iota`: https://yourbasic.org/golang/iota/ (строковое представление необязательно)
3. В go константы не прописываются капсом, используй PascalCase
4. Здесь лучше сделать по-другому: на вход `NewStorage` может приходить объект конфигурации, который выглядит примерно так:

```go
struct Config type {
    InMemory *inMemoryConfig.Config
    File *fileConfig.Config
}
```

Тогда то поле, которое не равно `nil`, будет определять тип хранилища.

С этой точки зрения лучше имплементацию `in-memory` и `file` хранилищ вынести в отдельные пакеты внутри `storage`.

Кроме того имя папки `models` не очень хорошо подходит -- `models` модели данных, то есть объекты, у которых нет поведения, но которые используются другими компоненатми. Я бы поместил весь код, который относится к хранилищам, например, в папку `repository`

2024-11-22 13:53 UTC, s-shpak requested changes
См. комментарий

2024-11-22 13:53 UTC, s-shpak commented on internal/repository/storage_repo.go
> +type IStorage interface {
Как мы обсуждали, в Go интерфйсы не принято называть начиная с "I"

```suggestion
type Storage interface {
```

2024-11-23 15:01 UTC, s-shpak approved these changes

2024-11-23 19:17 UTC, merged